plugins {
    id "com.android.application"
}

android {
    namespace "com.forma.editor"
    compileSdk 17

    defaultConfig {
        applicationId "com.forma.editor"
        minSdk 26
        targetSdk 26
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
